"""user table

Revision ID: 6a37ce5b3c31
Revises: 
Create Date: 2020-05-26 12:42:31.955199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a37ce5b3c31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    op.drop_table('sell_transaction')
    op.drop_table('buy_transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('share_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price_per_share', sa.FLOAT(), nullable=False),
    sa.Column('num_shares', sa.FLOAT(), nullable=False),
    sa.Column('dollar_amount', sa.FLOAT(), nullable=False),
    sa.Column('date_bought', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('buy_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('share_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price_per_share', sa.FLOAT(), nullable=False),
    sa.Column('num_shares', sa.FLOAT(), nullable=False),
    sa.Column('dollar_amount', sa.FLOAT(), nullable=False),
    sa.Column('date_bought', sa.DATETIME(), nullable=False),
    sa.Column('date_sold', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['buy_id'], ['buy_transaction.id'], ),
    sa.ForeignKeyConstraint(['date_bought'], ['buy_transaction.date_bought'], ),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
